baseURL = 'https://clojure-phrasebook.composed.ch'
languageCode = 'en-us'
title = 'Clojure Phrasebook'

[minify]
minifyOutput = true

[params]
math = false
openapi = false
showVisitedLinks = true

[params.author]
name = 'Patrick Bucher, Composed GmbH'

[[params.themeVariant]]
identifier = 'relearn-light'

[[params.themeVariant]]
identifier = 'relearn-dark'

[module]
[[module.imports]]
path = 'github.com/McShelby/hugo-theme-relearn'
